import React,{useMemo} from 'react';
import * as XLSX from 'xlsx';
import {Download,FileBarChart,AlertTriangle,PackageX} from 'lucide-react';
import {Order,StockRecord} from '../types';
import {getTodayDateString,isOrderToday,isOrderUnfinished} from '../utils/orderStatus';
import {getUpdatedStockRecord} from '../utils/stockData';

export function DailyReport({orders,stockRecords}:{orders:Order[];stockRecords:StockRecord[]}){
 const todayOrders=useMemo(()=>orders.filter(o=>isOrderToday(o.date)),[orders]);
 const incomplete=useMemo(()=>todayOrders.filter(isOrderUnfinished),[todayOrders]);
 const stock=useMemo(()=>stockRecords.map(s=>getUpdatedStockRecord(s,orders)).filter(s=>s.availableStock===0||s.availableStock<s.minimumLimit),[stockRecords,orders]);
 const totalValue=todayOrders.reduce((n,o)=>n+o.value,0);
 const reason=(o:Order)=>o.notes?.trim()||(o.items.some(i=>{const s=stockRecords.find(x=>x.name.trim().toLowerCase()===i.name.trim().toLowerCase());return !s||s.availableStock<i.pending})?'Stock unavailable / insufficient':'Pending packing or dispatch');
 const download=()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(todayOrders.map(o=>({'Company':o.companyName,'Voucher':o.voucherNumber,'SK Number':o.skNumber||'','Order Value':o.value,'Status':isOrderUnfinished(o)?'Incomplete':'Completed','Reason if incomplete':isOrderUnfinished(o)?reason(o):''}))),'Daily Orders');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(stock.map(s=>({'SKU':s.sku,'Item':s.name,'Available':s.availableStock,'Minimum':s.minimumLimit,'Status':s.availableStock===0?'OUT OF STOCK':'LOW STOCK','Shortage':s.shortageQuantity}))),'Stock Decision');XLSX.writeFile(wb,`ABC_Paints_Daily_Report_${getTodayDateString()}.xlsx`)};
 return <div className="space-y-4"><div className="bg-white rounded-2xl border p-5 flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between"><div><div className="flex items-center gap-2"><FileBarChart className="w-5 h-5 text-blue-600"/><h2 className="font-bold text-lg">Daily Decision Report</h2></div><p className="text-xs text-slate-500 mt-1">Today’s order value, incomplete-order reasons, and stock issues requiring action.</p></div><button onClick={download} className="bg-slate-900 text-white rounded-xl px-4 py-2.5 text-sm font-semibold flex items-center gap-2"><Download className="w-4 h-4"/>Download Report</button></div>
 <div className="grid sm:grid-cols-3 gap-3"><Card label="Today Order Value" value={`₹${totalValue.toLocaleString('en-IN')}`}/><Card label="Incomplete Today" value={String(incomplete.length)}/><Card label="Stock Problems" value={String(stock.length)}/></div>
 <div className="grid xl:grid-cols-2 gap-4"><div className="bg-white rounded-2xl border overflow-hidden"><div className="p-4 border-b flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-amber-600"/><b>Why Today’s Orders Are Incomplete</b></div><div className="overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Party / Order</th><th className="p-3 text-left">Reason</th><th className="p-3 text-right">Pending</th></tr></thead><tbody>{incomplete.map(o=><tr key={o.id} className="border-t"><td className="p-3"><b>{o.companyName}</b><div className="text-xs text-slate-500">{o.voucherNumber}</div></td><td className="p-3">{reason(o)}</td><td className="p-3 text-right font-bold">{o.pending}</td></tr>)}{!incomplete.length&&<tr><td colSpan={3} className="p-8 text-center text-slate-500">No incomplete orders received today.</td></tr>}</tbody></table></div></div>
 <div className="bg-white rounded-2xl border overflow-hidden"><div className="p-4 border-b flex items-center gap-2"><PackageX className="w-4 h-4 text-rose-600"/><b>Stock Decision Report</b></div><div className="overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Item</th><th className="p-3 text-left">Decision Status</th><th className="p-3 text-right">Available / Min</th></tr></thead><tbody>{stock.map(s=><tr key={s.id} className="border-t"><td className="p-3"><b>{s.name}</b><div className="text-xs text-slate-500">{s.sku}</div></td><td className="p-3"><span className={s.availableStock===0?'text-rose-700 font-bold':'text-amber-700 font-bold'}>{s.availableStock===0?'OUT OF STOCK':'LOW STOCK'}</span></td><td className="p-3 text-right">{s.availableStock} / {s.minimumLimit}</td></tr>)}{!stock.length&&<tr><td colSpan={3} className="p-8 text-center text-slate-500">No stock problems recorded.</td></tr>}</tbody></table></div></div></div></div>
}
function Card({label,value}:{label:string;value:string}){return <div className="bg-white rounded-2xl border p-5"><div className="text-xs text-slate-500">{label}</div><div className="text-2xl font-bold mt-1">{value}</div></div>}
