import React,{useEffect,useMemo,useRef,useState} from 'react';
import * as XLSX from 'xlsx';
import {Search,MapPin,Plus,Trash2,UploadCloud,Download} from 'lucide-react';
import {Order} from '../types';
import {AreaEntry,AreaClass,loadAreas,saveAreas} from '../utils/areaStore';
import {loadDbAreas,saveDbAreas} from '../utils/api';

const clean=(v:any)=>String(v??'').trim();
const header=(v:any)=>clean(v).toLowerCase().replace(/[^a-z]/g,'');

export function AreasDashboard({orders}:{orders:Order[]}){
 const [areas,setAreas]=useState<AreaEntry[]>(()=>loadAreas());
 const [search,setSearch]=useState(''); const [selected,setSelected]=useState<string[]>([]);
 const [code,setCode]=useState(''); const [company,setCompany]=useState(''); const [cls,setCls]=useState<AreaClass>('Local');
 const [message,setMessage]=useState(''); const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{
  let active=true;
  const bundled=loadAreas();
  const refresh=()=>loadDbAreas().then(async(rows)=>{
   if(!active)return;
   if(Array.isArray(rows)&&rows.length>0){setAreas(rows);saveAreas(rows);return}
   setAreas(bundled);saveAreas(bundled);
   try{await saveDbAreas(bundled,'Initial 3-Year Analysis area data')}catch{}
  }).catch(()=>{/* Keep the permanently saved browser copy when Streamlit has no API route. */});
  refresh();const timer=window.setInterval(refresh,10000);return()=>{active=false;window.clearInterval(timer)};
 },[]);
 const persist=async(next:AreaEntry[],source='Manual area update')=>{setAreas(next);saveAreas(next);try{await saveDbAreas(next,source);setMessage(`${message||'Areas updated'} Saved permanently in PostgreSQL.`)}catch{setMessage(`${message||'Areas updated'} Database unavailable; saved in this browser.`)}};
 const stats=useMemo(()=>{const m=new Map<string,{n:number;q:number}>();orders.filter(o=>o.pending>0).forEach(o=>{const k=o.companyName.trim().toUpperCase();const x=m.get(k)||{n:0,q:0};x.n++;x.q+=o.pending;m.set(k,x)});return m},[orders]);
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return areas.filter(a=>!q||a.areaCode.toLowerCase().includes(q)||a.companyName.toLowerCase().includes(q)||a.classification.toLowerCase().includes(q)).sort((a,b)=>a.areaCode.localeCompare(b.areaCode,undefined,{numeric:true,sensitivity:'base'})||a.companyName.localeCompare(b.companyName,undefined,{sensitivity:'base'}))},[areas,search]);
 const add=()=>{if(!code.trim()||!company.trim()){setMessage('Enter both Area Code and Company Name.');return}const id=`manual-${Date.now()}`;setMessage(`${cls} area added.`);persist([...areas,{id,code:id,areaCode:code.trim(),companyName:company.trim(),classification:cls,custom:true}],`${cls} manual entry`);setCode('');setCompany('')};
 const remove=()=>{persist(areas.filter(a=>!selected.includes(a.id)));setSelected([]);setMessage('Selected area records removed.')};
 const move=(classification:AreaClass)=>{setMessage(`${selected.length} record(s) moved to ${classification}.`);persist(areas.map(a=>selected.includes(a.id)?{...a,classification}:a),`Classified as ${classification}`);setSelected([])};
 const downloadTemplate=()=>{const ws=XLSX.utils.json_to_sheet([{'Area Code':'','Company Name':'','Area Type':'Local'}]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Areas');XLSX.writeFile(wb,'ABC_Paints_Areas_Import_Template.xlsx')};
 const importFile=async(file:File)=>{try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const parsed:AreaEntry[]=[];for(const sheetName of wb.SheetNames){const rows=XLSX.utils.sheet_to_json<any[]>(wb.Sheets[sheetName],{header:1,defval:''});const h=rows.findIndex(r=>r.some(v=>header(v)==='areacode')&&r.some(v=>['companyname','party','partyasperreport'].includes(header(v))));if(h<0)continue;const heads=rows[h].map(header);const ai=heads.findIndex(x=>x==='areacode');const ci=heads.findIndex(x=>['code','customercode'].includes(x));const pi=heads.findIndex(x=>['companyname','party','partyasperreport'].includes(x));const ti=heads.findIndex(x=>['areatype','type','classification'].includes(x));rows.slice(h+1).forEach((row,i)=>{const codeValue=clean(ci>=0?row[ci]:'')||`file-${Date.now()}-${parsed.length}`;const areaCode=clean(row[ai]);let companyName=clean(row[pi]);if(companyName.toUpperCase().startsWith(codeValue.toUpperCase()))companyName=companyName.slice(codeValue.length).trim();if(areaCode&&companyName.toUpperCase().endsWith(areaCode.toUpperCase()))companyName=companyName.slice(0,-areaCode.length).trim();const rawType=clean(ti>=0?row[ti]:'').toLowerCase();const classification:AreaClass=rawType.startsWith('t')?'Transport':rawType.startsWith('l')?'Local':'';if(companyName)parsed.push({id:`db-${codeValue}`,code:codeValue,areaCode,companyName,classification,custom:true})})}if(!parsed.length)throw new Error('No customer/area rows found');const seen=new Map(areas.map(a=>[(a as any).code||a.id,a]));parsed.forEach(a=>seen.set((a as any).code||a.id,a));setMessage(`${parsed.length} customer-area records imported from ${file.name}.`);await persist(Array.from(seen.values()),file.name)}catch(e:any){setMessage(e.message||'Area file could not be read.')}finally{if(fileRef.current)fileRef.current.value=''}};
 return <div className="space-y-4">
  <div className="bg-white rounded-2xl border p-5">
   <div className="flex flex-col lg:flex-row gap-3 lg:items-center justify-between"><div><div className="flex items-center gap-2"><MapPin className="w-5 h-5 text-blue-600"/><h2 className="font-semibold">Areas Master</h2></div><p className="text-xs text-slate-500 mt-1">The 3-Year Analysis customers are loaded here for classification into Local or Transport and saved permanently in PostgreSQL.</p></div><div className="flex flex-wrap gap-2"><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/><button onClick={()=>fileRef.current?.click()} className="border rounded-xl px-3 py-2 text-xs font-semibold flex items-center gap-1"><UploadCloud className="w-4 h-4"/>Import Areas File</button><button onClick={downloadTemplate} className="border rounded-xl px-3 py-2 text-xs font-semibold flex items-center gap-1"><Download className="w-4 h-4"/>Download Template</button></div></div>
   <div className="grid md:grid-cols-[1fr_2fr_160px_auto] gap-2 mt-4"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Area code" className="border rounded-xl px-3 py-2 text-sm"/><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Company / party name" className="border rounded-xl px-3 py-2 text-sm"/><select value={cls} onChange={e=>setCls(e.target.value as AreaClass)} className="border rounded-xl px-3 py-2 text-sm"><option>Local</option><option>Transport</option></select><button onClick={add} className="bg-slate-900 text-white rounded-xl px-4 py-2 text-sm font-semibold flex items-center justify-center gap-1"><Plus className="w-4 h-4"/>Add</button></div>
   {message&&<div className="mt-3 text-xs font-medium text-blue-700">{message}</div>}
  </div>
  <div className="bg-white rounded-2xl border overflow-hidden"><div className="p-4 border-b flex items-center justify-between"><div><b>Unclassified Customers</b><div className="text-xs text-slate-500">Select records, then move them to Local or Transport.</div></div><span className="text-sm font-bold">{filtered.filter(a=>!a.classification).length}</span></div><div className="max-h-72 overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-slate-50"><tr><th className="p-3"></th><th className="p-3 text-left">Area Code</th><th className="p-3 text-left">Company</th><th className="p-3 text-left">Customer Code</th></tr></thead><tbody>{filtered.filter(a=>!a.classification).map(a=><tr key={a.id} className="border-t"><td className="p-3 text-center"><input type="checkbox" checked={selected.includes(a.id)} onChange={()=>setSelected(s=>s.includes(a.id)?s.filter(x=>x!==a.id):[...s,a.id])}/></td><td className="p-3 font-semibold">{a.areaCode||'—'}</td><td className="p-3">{a.companyName}</td><td className="p-3 font-mono text-xs">{(a as any).code||a.id.replace(/^db-/,'')}</td></tr>)}</tbody></table></div><div className="p-3 border-t flex gap-2"><button disabled={!selected.length} onClick={()=>move('Local')} className="bg-blue-600 text-white rounded-lg px-3 py-2 text-xs font-semibold disabled:opacity-40">Add to Local</button><button disabled={!selected.length} onClick={()=>move('Transport')} className="bg-amber-600 text-white rounded-lg px-3 py-2 text-xs font-semibold disabled:opacity-40">Add to Transport</button></div></div>
  <div className="grid md:grid-cols-2 gap-4">{(['Local','Transport'] as AreaClass[]).map(group=>{const rows=filtered.filter(a=>a.classification===group);return <div key={group} className="bg-white rounded-2xl border overflow-hidden"><div className="p-4 border-b flex items-center justify-between"><div><b>{group} Areas</b><div className="text-xs text-slate-500">{rows.length} records</div></div><button disabled={!selected.length} onClick={()=>move(group)} className="text-xs border rounded-lg px-3 py-1.5 disabled:opacity-40">Move selected here</button></div><div className="p-3 border-b relative"><Search className="absolute left-6 top-5 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search area or company" className="w-full border rounded-xl pl-9 pr-3 py-2 text-sm"/></div><div className="max-h-[520px] overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-slate-50"><tr><th className="p-3"></th><th className="p-3 text-left">Area Code</th><th className="p-3 text-left">Company</th><th className="p-3 text-right">Pending</th></tr></thead><tbody>{rows.map(a=>{const st=stats.get(a.companyName.trim().toUpperCase())||{n:0,q:0};return <tr key={a.id} className="border-t"><td className="p-3 text-center"><input type="checkbox" checked={selected.includes(a.id)} onChange={()=>setSelected(s=>s.includes(a.id)?s.filter(x=>x!==a.id):[...s,a.id])}/></td><td className="p-3 font-semibold">{a.areaCode}</td><td className="p-3">{a.companyName}</td><td className="p-3 text-right">{st.n} / {st.q.toLocaleString('en-IN')}</td></tr>})}{!rows.length&&<tr><td colSpan={4} className="p-10 text-center text-slate-500">No {group.toLowerCase()} areas added yet.</td></tr>}</tbody></table></div></div>})}</div>
  <button disabled={!selected.length} onClick={remove} className="bg-red-600 text-white rounded-xl px-4 py-2 text-xs font-semibold disabled:opacity-40 inline-flex items-center gap-1"><Trash2 className="w-4 h-4"/>Remove Selected</button>
 </div>
}

